version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - PROD_DB_URL=jdbc:mysql://db:3306/expense_tracking
      - PROD_DB_USERNAME=expenseapp
      - PROD_DB_PASSWORD=your_secure_password
      - JWT_SECRET=your_secure_jwt_secret
    depends_on:
      - db
    volumes:
      - /var/log/expense-tracking:/var/log/expense-tracking
    restart: unless-stopped
    
  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=expense_tracking
      - MYSQL_USER=expenseapp
      - MYSQL_PASSWORD=your_secure_password
      - MYSQL_ROOT_PASSWORD=your_secure_root_password
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped

volumes:
  mysql_data:
